name: use Github App
on: 
  workflow_dispatch:

  push:
    paths:
      - use-github-app.yml
jobs:
  checkout-other-repo:
    runs-on: ubuntu-latest
    steps:
    - name: Get token
      id: get_workflow_token
      uses: nahimanajz/workflow-application-token-action@v2
      with:
        application_id: ${{ vars.GH_APPLICATION_ID }}
        application_private_key: ${{ secrets.GH_APPLICATION_KEY }}
    - run: |
         git clone "https://x:${{ steps.get_workflow_token.outputs.token }}@github.com/nahimanajz/demo-actions.git"

